---
name: pr_all

on:
  pull_request:
    branches:
      - master
    paths:
      - "info.yaml"

jobs:
  always-runs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this always runs"

      - name: Workflow info
        run: |
          echo This workflow is running against commit "${{ github.sha }}"

          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks/${GITHUB_RUN_ID}"

          echo "github.repository: ${{github.repository}}"
          echo "github.sha: ${{github.sha}}"
          echo "github.run_id: ${{github.run_id}}"
          echo "https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"

          echo "github.server_url: ${{github.server_url}}"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          echo "github.pull_request.url: ${{github.pull_request.url}}"
          echo "github.pull_request.html_url: ${{github.pull_request.html_url}}"
          echo "github.pull_request.issue_url: ${{github.pull_request.issue_url}}"
          echo "github.pull_request.comments_url: ${{github.pull_request.comments_url}}"
          echo "github.pull_request.statuses_url: ${{github.pull_request.statuses_url}}"

          echo "github.event.pull_request.url: ${{github.event.pull_request.url}}"
          echo "github.event.pull_request.html_url: ${{github.event.pull_request.html_url}}"
          echo "github.event.pull_request.issue_url: ${{github.event.pull_request.issue_url}}"
          echo "github.event.pull_request.comments_url: ${{github.event.pull_request.comments_url}}"
          echo "github.event.pull_request.statuses_url: ${{github.event.pull_request.statuses_url}}"

          echo "github.action: ${{github.action}}"
          echo "github.action_path: ${{github.action_path}}"
          echo "github.action_ref: ${{github.action_ref}}"
          echo "github.action_repository: ${{github.action_repository}}"
          echo "github.action_status: ${{github.action_status}}"
          echo "github.actor: ${{github.actor}}"
          echo "github.actor_id: ${{github.actor_id}}"
          echo "github.api_url: ${{github.api_url}}"
          echo "github.base_ref: ${{github.base_ref}}"
          echo "github.env: ${{github.env}}"
          echo "github.event: ${{github.event}}"
          echo "github.event_name: ${{github.event_name}}"
          echo "github.event_path: ${{github.event_path}}"
          echo "github.graphql_url: ${{github.graphql_url}}"
          echo "github.head_ref: ${{github.head_ref}}"
          echo "github.job: ${{github.job}}"
          echo "github.job_workflow_sha: ${{github.job_workflow_sha}}"
          echo "github.path: ${{github.path}}"
          echo "github.ref: ${{github.ref}}"
          echo "github.ref_name: ${{github.ref_name}}"
          echo "github.ref_protected: ${{github.ref_protected}}"
          echo "github.ref_type: ${{github.ref_type}}"
          echo "github.repository: ${{github.repository}}"
          echo "github.repository_id: ${{github.repository_id}}"
          echo "github.repository_owner: ${{github.repository_owner}}"
          echo "github.repository_owner_id: ${{github.repository_owner_id}}"
          echo "github.repositoryUrl: ${{github.repositoryUrl}}"
          echo "github.retention_days: ${{github.retention_days}}"
          echo "github.run_id: ${{github.run_id}}"
          echo "github.run_number: ${{github.run_number}}"
          echo "github.run_attempt: ${{github.run_attempt}}"
          echo "github.secret_source: ${{github.secret_source}}"
          echo "github.server_url: ${{github.server_url}}"
          echo "github.sha: ${{github.sha}}"
          echo "github.token: ${{github.token}}"
          echo "github.triggering_actor: ${{github.triggering_actor}}"
          echo "github.workflow: ${{github.workflow}}"
          echo "github.workflow_ref: ${{github.workflow_ref}}"
          echo "github.workflow_sha: ${{github.workflow_sha}}"
          echo "github.workspace: ${{github.workspace}}"

          echo "job: ${{job}}"
          echo "job.container: ${{job.container}}"
          echo "job.container.id: ${{job.container.id}}"
          echo "job.container.network: ${{job.container.network}}"
          echo "job.services: ${{job.services}}"
          echo "job.status: ${{job.status}}"

  runs-when-merged-1:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - run: echo "this runs when the PR is merged 1"

  runs-when-closed:
    runs-on: ubuntu-latest
    if: not(github.event.pull_request.merged)
    steps:
      - run: echo "this runs when the PR is closed but not merged"
