name: pr_closed

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  notify_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: prepare and send message
        run: |
          echo -n '' > msg-slack.json
          echo -n '{"text":"The following PR has been merged:\n' >> msg-slack.json
          echo -n '${{github.event.pull_request.title}} [\#${{github.event.pull_request.number}}](${{github.event.pull_request.html_url }})\n' >> msg-slack.json
          echo -n 'Opened by ${{github.event.pull_request.user.login }}\n ' >> msg-slack.json
          echo -n 'Commits: \n' >> msg-slack.json
          curl ${{ github.event.pull_request.commits_url }} | jq -r '.[] | " * " + .sha[:8] + " " + .commit.message' | perl -npe 's/\n/\\n/g' >> msg-slack.json
          echo -n '"}' >> msg-slack.json
          echo '' >> msg-slack.json
          curl -v ${{ secrets.SLACK_WEBHOOK_URL }} \
            -X POST \
            --data @msg-slack.json \
            -H "Content-Type: application/json"
