---
name: pr_closed

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
#  notify_merged:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: on_pr_closed prepare and send message
#        run: |
#          export GITHUB_EVENT_PULL_REQUEST_TITLE="${{ github.event.pull_request.title }}"
#          export GITHUB_EVENT_PULL_REQUEST_HTML_URL="${{ github.event.pull_request.html_url }}"
#          export GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}"
#          export GITHUB_EVENT_PULL_REQUEST_USER_LOGIN="${{ github.event.pull_request.user.login }}"
#          export LIST_OF_COMMITS=$(curl ${{ github.event.pull_request.commits_url }} | jq -r '.[] | " - " + .sha[:8] + " " + .commit.message' | perl -npe 's/\n/\\n/g')
#          echo "LIST_OF_COMMITS: :::$LIST_OF_COMMITS:::"
#          cat $GITHUB_WORKSPACE/.github/workflows/merge_template.txt | envsubst > msg-slack.json
#          echo "At this point, send a message some-whither, to the effect that the PR was merged."

  always-runs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this always runs"

      - name: Workflow info
        run: |
          echo This workflow is running against commit "${{ github.sha }}"

          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks/${GITHUB_RUN_ID}"

          echo "github.repository: ${{github.repository}}"
          echo "github.sha: ${{github.sha}}"
          echo "github.run_id: ${{github.run_id}}"
          echo "https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"

          echo "github.server_url: ${{github.server_url}}"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  runs-when-merged-1:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - run: echo "this runs when the PR is merged 1"

  runs-when-merged-2:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo "this runs when the PR is merged 2"

  runs-when-merged-3:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - run: echo "this runs when the PR is merged 3"

  runs-when-merged-4:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - run: echo "this runs when the PR is merged 4"

  runs-when-closed:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == false }}
    steps:
      - run: echo "this runs when the PR is closed but not merged"
