# This is a basic workflow to help you get started with Actions

name: push

on:
  push:
    branches:
      - master

jobs:
  print_values:
    runs-on: ubuntu-latest
    steps:
      - name: print values
        run: |
          echo github.event: ${{ github.event }}
          echo github.event_name: ${{ github.event_name }}
          echo github.event.action: ${{ github.event.action }}
          echo github.event.client_payload.versions: ${{ github.event.client_payload.versions }}
          echo github.event.push: ${{ github.event.push }}
          echo github.event.push.push_id: ${{ github.event.push.push_id }}
          echo github.event.push.size: ${{ github.event.push.size }}
          echo github.event.push.distinct_size: ${{ github.event.push.distinct_size }}
          echo github.event.push.ref: ${{ github.event.push.ref }}
          echo github.event.push.head: ${{ github.event.push.head }}
          echo github.event.push.before: ${{ github.event.push.before }}
          echo github.event.push.commits: ${{ github.event.push.commits }}
          echo -n 'node:    ' ; which node
          echo -n 'python:  ' ; which python
          echo -n 'python2: ' ; which python2
          echo -n 'python3: ' ; which python3
          echo -n 'go:      ' ; which go
          echo -n 'gcc:     ' ; which gcc
          echo -n 'perl:    ' ; which perl
          echo -n 'jq:      ' ; which jq
#  notify_of_push:
#    runs-on: ubuntu-latest
#    steps:
      - name: prepare and send message
        run: |
          echo -n '' > msg.json
          echo -n '{"channel":"#test","text":"Someone (maybe ${{ github.event.push.pusher.name }}) pushed directly to master\n' >> msg.json
          echo -n '"}' >> msg.json
          echo '' >> msg.json
          echo ":::::::::::::::"
          cat msg.json
          echo ":::::::::::::::"
          curl -v ${{ secrets.ROCKET_CHAT_SERVER_URI }}/api/v1/chat.postMessage \
            -X POST \
            --data @msg.json \
            -H "X-Auth-Token: ${{ secrets.ROCKET_CHAT_TOKEN }}" \
            -H "X-User-Id: ${{ secrets.ROCKET_CHAT_USER_ID }}" \
            -H "Content-Type: application/json"
