
name: push

on:
  push:
    branches:
      - master

jobs:
  notify_push_without_pr:
    runs-on: ubuntu-latest
    steps:
      - name: prepare and send message
        run: |
          url=${{ github.event.repository.commits_url }}
          commit_sha=${{ github.event.after }}
          commit_url=$(echo $url | sed s/\{\\/sha\}/\\/$commit_sha/)
          curl "$commit_url" > commit.json
          is_push_without_pr=$(
            cat commit.json | jq '(.parents | length < 2) or
             ((.commit.committer.name != "GitHub") and
              (.commit.committer.email != "noreply@github.com") and
              (.committer.login != "web-flow") and
              (.commit.message | startswith("Merge pull request #") | not ))')
          if [[ "$is_push_without_pr" = 'true' ]]; then
            echo -n '' > msg-slack.json
            echo -n '{"text":"${{ github.event.pusher.name }} pushed directly to master\n' >> msg-slack.json
            echo -n 'Compare here: ${{ github.event.compare }}\n' >> msg-slack.json
            echo -n '"}' >> msg-slack.json
            echo '' >> msg-slack.json
            curl -v ${{ secrets.SLACK_WEBHOOK_URL }} \
              -X POST \
              --data @msg-slack.json \
              -H "Content-Type: application/json"
          fi
