
name: push

on:
  push:
    branches:
      - master

jobs:
  notify_push_without_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: on_push prepare and send message
        run: |
          url=${{ github.event.repository.commits_url }}
          commit_sha=${{ github.event.after }}
          commit_url=$(echo $url | sed s/\{\\/sha\}/\\/$commit_sha/)
          curl "$commit_url" > commit.json
          is_push_without_pr=$(
            cat commit.json | jq '(.parents | length < 2) or
             ((.commit.committer.name != "GitHub") and
              (.commit.committer.email != "noreply@github.com") and
              (.committer.login != "web-flow") and
              (.commit.message | startswith("Merge pull request #") | not ))')
          if [[ "$is_push_without_pr" = 'true' ]]; then
            export GITHUB_EVENT_PUSHER_NAME="${{ github.event.pusher.name }}"
            export GITHUB_EVENT_COMPARE="${{ github.event.compare }}"
            cat $GITHUB_WORKSPACE/.github/workflows/push_template.txt | envsubst > msg-slack.json 
            curl -v ${{ secrets.SLACK_WEBHOOK_URL }} \
              -X POST \
              --data @msg-slack.json \
              -H "Content-Type: application/json"
          fi
