
name: push

on:
  push:
    branches:
      - master

jobs:
  notify_push_without_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check envsubst
        run: |
          echo -n 'envsubst: ' ; which envsubst || true
          echo -n 'j2cli: ' ; which j2cli || true
          pwd
          ls -la $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE/.github/workflows/push_template.txt
          find $GITHUB_WORKSPACE -name message_format.txt
      - name: prepare merge message
        run: |
          export GITHUB_EVENT_PULL_REQUEST_TITLE="${{ github.event.pull_request.title }}"
          export GITHUB_EVENT_PULL_REQUEST_HTML_URL="${{ github.event.pull_request.html_url }}"
          export GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}"
          export GITHUB_EVENT_PULL_REQUEST_USER_LOGIN="${{ github.event.pull_request.user.login }}"
          export LIST_OF_COMMITS=$(curl ${{ github.event.pull_request.commits_url }} | jq -r '.[] | " - " + .sha[:8] + " " + .commit.message' | perl -npe 's/\n/\\n/g' >> msg-slack.json)
          echo "LIST_OF_COMMITS: :::$LIST_OF_COMMITS:::"
          cat $GITHUB_WORKSPACE/.github/workflows/merge_template.txt | envsubst > msg-slack.json
          cat msg-slack.json
      - name: prepare and send message
        run: |
          url=${{ github.event.repository.commits_url }}
          commit_sha=${{ github.event.after }}
          commit_url=$(echo $url | sed s/\{\\/sha\}/\\/$commit_sha/)
          curl "$commit_url" > commit.json
          is_push_without_pr=$(
            cat commit.json | jq '(.parents | length < 2) or
             ((.commit.committer.name != "GitHub") and
              (.commit.committer.email != "noreply@github.com") and
              (.committer.login != "web-flow") and
              (.commit.message | startswith("Merge pull request #") | not ))')
          if [[ "$is_push_without_pr" = 'true' ]]; then
            export GITHUB_EVENT_PUSHER_NAME="${{ github.event.pusher.name }}"
            export GITHUB_EVENT_COMPARE="${{ github.event.compare }}"
            cat $GITHUB_WORKSPACE/.github/workflows/push_template.txt | envsubst > msg-slack.json 
            curl -v ${{ secrets.SLACK_WEBHOOK_URL }} \
              -X POST \
              --data @msg-slack.json \
              -H "Content-Type: application/json"
          fi
