# This is a basic workflow to help you get started with Actions

name: push

on:
  push:
    branches:
      - master

jobs:
  print_values:
    runs-on: ubuntu-latest
    steps:
      - name: print values
        run: |
          echo github: ${{ github }}
          echo github.action: ${{ github.action }}
          echo github.action_path: ${{ github.action_path }}
          echo github.action_ref: ${{ github.action_ref }}
          echo github.action_repository: ${{ github.action_repository }}
          echo github.action_status: ${{ github.action_status }}
          echo github.actor: ${{ github.actor }}
          echo github.api_url: ${{ github.api_url }}
          echo github.base_ref: ${{ github.base_ref }}
          echo github.env: ${{ github.env }}
          echo github.api_url: ${{ github.api_url }}
          echo github.graphql_url: ${{ github.graphql_url }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.job: ${{ github.job }}
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.ref_protected: ${{ github.ref_protected }}
          echo github.ref_type: ${{ github.ref_type }}
          echo github.path: ${{ github.path }}
          echo github.repository: ${{ github.repository }}
          echo github.repository_owner: ${{ github.repository_owner }}
          echo github.repositoryUrl: ${{ github.repositoryUrl }}
          echo github.repositoryUrl: ${{ github.repositoryUrl }}
          echo github.retention_days: ${{ github.retention_days }}
          echo github.run_id: ${{ github.run_id }}
          echo github.run_number: ${{ github.run_number }}
          echo github.run_attempt: ${{ github.run_attempt }}
          echo github.server_url: ${{ github.server_url }}
          echo github.sha: ${{ github.sha }}
          echo github.token: ${{ github.token }}
          echo github.workflow: ${{ github.workflow }}
          echo github.workspace: ${{ github.workspace }}
          echo github.run_attempt: ${{ github.run_attempt }}
          echo github.run_attempt: ${{ github.run_attempt }}
          echo github.run_attempt: ${{ github.run_attempt }}
          echo github.run_attempt: ${{ github.run_attempt }}
          echo ''
          echo github.event: ${{ github.event }}
          echo github.event_name: ${{ github.event_name }}
          echo github.event_path: ${{ github.event_path }}
          echo github.event.action: ${{ github.event.action }}
          echo github.event.client_payload.versions: ${{ github.event.client_payload.versions }}
          echo github.event.push: ${{ github.event.push }}
          echo github.event.push.push_id: ${{ github.event.push.push_id }}
          echo github.event.push.size: ${{ github.event.push.size }}
          echo github.event.push.distinct_size: ${{ github.event.push.distinct_size }}
          echo github.event.push.ref: ${{ github.event.push.ref }}
          echo github.event.push.head: ${{ github.event.push.head }}
          echo github.event.push.before: ${{ github.event.push.before }}
          echo github.event.push.commits: ${{ github.event.push.commits }}
          echo ''
          echo github.event.push_id: ${{ github.event.push_id }}
          echo github.event.size: ${{ github.event.size }}
          echo github.event.distinct_size: ${{ github.event.distinct_size }}
          echo github.event.ref: ${{ github.event.ref }}
          echo github.event.head: ${{ github.event.head }}
          echo github.event.before: ${{ github.event.before }}
          echo github.event.commits: ${{ github.event.commits }}
          echo ''
          echo github.event.ref: ${{ github.event.ref }}
          echo github.event.before: ${{ github.event.before }}
          echo github.event.after: ${{ github.event.after }}
          echo github.event.created: ${{ github.event.created }}
          echo github.event.deleted: ${{ github.event.deleted }}
          echo github.event.forced: ${{ github.event.forced }}
          echo github.event.head_commit: ${{ github.event.head_commit }}
          echo github.event.compare: ${{ github.event.compare }}
          echo github.event.commits: ${{ github.event.commits }}
          echo github.event.pusher: ${{ github.event.pusher }}
          echo github.event.repository: ${{ github.event.repository }}
          echo github.event.repository.name: ${{ github.event.repository.name }}
          echo github.event.repository.owner: ${{ github.event.repository.owner }}
          echo github.event.repository.nameWithOwner: ${{ github.event.repository.nameWithOwner }}
          echo github.event.repository.name_with_owner: ${{ github.event.repository.name_with_owner }}
          echo github.event.repository: ${{ github.event.repository }}
          echo github.event.organization: ${{ github.event.organization }}
          echo github.event.installation: ${{ github.event.installation }}
          echo github.event.sender: ${{ github.event.sender }}
          echo ''
          echo github.event.pull_request: ${{ github.event.pull_request }}
          echo ''
          echo '${{ toJSON(github) }}'
          echo ''
          echo -n 'node:    ' ; which node
          echo -n 'python:  ' ; which python
          echo -n 'python2: ' ; which python2
          echo -n 'python3: ' ; which python3
          echo -n 'go:      ' ; which go
          echo -n 'gcc:     ' ; which gcc
          echo -n 'perl:    ' ; which perl
          echo -n 'jq:      ' ; which jq
#  notify_of_push:
#    runs-on: ubuntu-latest
#    steps:
      - name: prepare and send message
        run: |
          echo -n '' > msg.json
          echo -n '{"channel":"#test","text":"Someone (maybe ${{ github.event.pusher.name }}) pushed directly to master\n' >> msg.json
          echo -n 'Compare here: ${{ github.event.compare }}\n' >> msg.json
          echo -n '"}' >> msg.json
          echo '' >> msg.json
          echo ":::::::::::::::"
          cat msg.json
          echo ":::::::::::::::"
          curl -v ${{ secrets.ROCKET_CHAT_SERVER_URI }}/api/v1/chat.postMessage \
            -X POST \
            --data @msg.json \
            -H "X-Auth-Token: ${{ secrets.ROCKET_CHAT_TOKEN }}" \
            -H "X-User-Id: ${{ secrets.ROCKET_CHAT_USER_ID }}" \
            -H "Content-Type: application/json"
